### PR TITLE
Add youdao translate.

### PR DESCRIPTION
**Pull request by MitsuhaMiyamizu**
Add youdao translate API, need to be sanitized and well tested from the owner ( @GuangchuangYu ) of this repository to see if this can be merged.  
I have tested from my side, but CRAN has a stricter standard for publishing packages.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
> `&vocabId=", "您的用户词表ID"`

I am wondering whether this is needed. 


In addition, can you update the [README](https://github.com/YuLab-SMU/fanyi?tab=readme-ov-file#to-use-bing-translate) to introduce this translate engine and how to get the appid and key

**Comment by GuangchuangYu** [comment]
PS: <https://github.com/YuLab-SMU/fanyi/blob/devel/R/baidu.R#L10-L11> this is much better than using a lot of `paste`.

**Comment by MitsuhaMiyamizu** [comment]
> > `&vocabId=", "您的用户词表ID"`
> 
> I am wondering whether this is needed.
> 
> In addition, can you update the [README](https://github.com/YuLab-SMU/fanyi?tab=readme-ov-file#to-use-bing-translate) to introduce this translate engine and how to get the appid and key

"User defined dictionary", which is more like a mapping relations between two sets, that is equation. And this can be left as an option for the user to choose from. I'll see if I can fix those 2 issues as quick as possible.

**Comment by MitsuhaMiyamizu** [comment]
Greetings! Readme has been added and code has been sanitized, you can test the code before merging this pull request.

**Comment by GuangchuangYu** [comment]
thanks, you can add your name in the DESCRIPTION as a contributor.

PS: the user-defined dictionary is supported.

**Comment by MitsuhaMiyamizu** [comment]
Ah, after reading your code, I just realized 2 principles of developing packages:
1. avoid introducing another multifunctional package (like stringr), use functions in base as possible as one can (atomic operations make vectorisation/parallelisation easier).
2. use list instead of excessive paste/paste0(s) to make it tidy and clean.

Thank you for helping out, Prof. Yu :)

**Pull request merged**
