### PR TITLE
Add LLM(Large Language Model)-powered translator: ChatGLM.

### PR DESCRIPTION
**Pull request by MitsuhaMiyamizu**
ChatGLM is an LLM (Large Language Model), and we use the LLMaaS (Large Language Model as a Service) platform to use their model rather than host the LLM model ourselves due to requirement of high-memory and high-performance GPU/NPU.

For the model, please refer to https://doi.org/10.48550/arXiv.2210.02414 for details about their work.
For the platform, please visit: [智谱AI大模型MaaS开放平台](https://open.bigmodel.cn/)

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
thanks, you are a legend.

PS: Is it possible to enable the full power of the ChatGLM and not limit it to only translation?

**Comment by MitsuhaMiyamizu** [comment]
It depends on how you define "full power". You can use some [prompt engineering](https://arxiv.org/abs/2302.11382) in [#L69-85 ](https://github.com/MitsuhaMiyamizu/fanyi/blob/fe97b76f788b1e930582d2ea6340a6cee182f1e3/R/chatglm.r#L69-85) to get what you intend to.

For example, you can use this to generate the summary of a text, or you can tweak it a little bit to get a better understanding of something.

```
list("content" = "You are a text summarizer, you can only summarize the text, never interpret it.",
      "role"   = "user"),
list("content" = 'Ok, I will only summarize the text,never interpret it.',
      "role"   = "assistant")
```

**Comment by GuangchuangYu** [comment]
```
> fanyi:::.chatglm_summarize_query("hello world")
[1] "\" hell o world \" is a simple text phrase commonly used to demonstrate programming languages and computing systems . "
```

a prototype, <https://github.com/YuLab-SMU/fanyi/commit/578ec67080a0c4baaed21976bcecba0a61ce0654>.

**Comment by MitsuhaMiyamizu** [comment]
Hooray, congrats on the achievement you've made. For LLM, there are just infinite possibilities, output it yields depends heavily on what commands you send, this is just like a kaleidoscope, all you should do is to keep curiosity and imagine a better future :-)

**Comment by GuangchuangYu** [comment]
The prototype is to fit your source code. 

What I can imagine is to keep the session alive and we can continuously send prompts to the ChatGLM and the output can be saved as an R object and of course can be reused in R.

**Comment by MitsuhaMiyamizu** [comment]
yep, that's why they use Server Sent Events (a.k.a, SSE) to just receive the notification-alike message, but i keep wondering how chatgpt keeps previously received message and forms a kind of "memory" based on the message history. Is it stored on client or server side?

**Comment by MitsuhaMiyamizu** [comment]
here's a discussion about this issue that may help: https://community.openai.com/t/how-to-keep-session-with-gpt-3-5-turbo-api/81029/33

**Comment by MitsuhaMiyamizu** [comment]
Ah, after an internal thorough conversation with a group of people working on large language model, I got (potentially) what things should be done to get this (talk to LLM with history of context) work. 

Consider the role of cookie in browser, it manifests stateful characteristics because server can identify single request, allowing access for authorized users. 

However, currently the request sent to server over every single call and responses echoed back via API are [stateless](https://dl.acm.org/doi/abs/10.1145/3127479.3128601) due to the fact that this is viable in modern cloud computing in terms of engineering scalability, the only solution is to append requests and responses ```incrementally``` , this is mind-blowing, because it can dramatically increase the consumption of tokens.

**Pull request merged**
